StackOfMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, CompletedMusicRetrieveView, CompletedMusicDetailTemplateView, LikeMusicAPIView, \
    LikeMusicUpdateAPI, CreateCommentView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('<int:completed_music_id>/', CompletedMusicDetailTemplateView.as_view(), name='completed_music_detail'),
    path('RetrieveAPI/<int:completed_music_id>/', CompletedMusicRetrieveView.as_view(), name='completed_music_detail_api'),
    path('LikeMusicAPI/<int:completed_music_id>', LikeMusicAPIView.as_view(), name='like_music_api'),
    path('LikeMusicUpdateAPI/<int:pk>', LikeMusicUpdateAPI, name='like_music_update'),
    path('<int:completed_music_id>/CreateComment', CreateCommentView.as_view(), name='create_comment'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('create/', include('createmusic.urls', namespace='create_music')),
    path('instrument/search/', include('instrument.urls', namespace='instrument_search')),
    path('s3direct/', include('s3direct.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import CreateUserView, CreateUserDoneView, UserLoginView, UserLogoutView, UserDetailView, \
    CopyrightTemplateView, UserWorkingProjects, MyPageListTemplateView, UserWorkingProjectsListView, \
    UserLikedMusicListView

app_name = 'accounts'


urlpatterns = [
    path('create/', CreateUserView.as_view(), name='accounts_create'),
    path('create/done', CreateUserDoneView.as_view(), name='accounts_create_done'),
    path('signin/', UserLoginView.as_view(), name='accounts_login'),
    path('signout/', UserLogoutView.as_view(url='http://localhost:8000'), name='accounts_logout'),
    path('mypage/<int:account_id>/myinfo', UserDetailView.as_view(), name='accounts_detail'),
    path('mypage/<int:account_id>/copyright/', CopyrightTemplateView.as_view(), name='accounts_copyright'),
    path('mypage/<int:account_id>/myworkingmusic/', UserWorkingProjectsListView.as_view(), name='accounts_working_projects'),
    path('mypage/<int:account_id>', MyPageListTemplateView.as_view(), name='account_list'),
    path('mypage/<int:account_id>/LkeMusic', UserLikedMusicListView.as_view(), name='user_liked_music'),
]

createmusic/urls.py
from django.urls import path

from .views import CreateMusicView, WorkingMusicListView, WorkingMusicDeleteView, WorkingMusicRetrieveView, \
    WorkingMusicRetrieveTemplateView, SubMusicMergeView, SubMusicCreateView, MusicStatusChangeView, SubMusicDeleteView, \
    VoiceToDrumView, VoiceToPianoView, LoopStationView, MusicConvertCheckView, MusicCompletedView


app_name = 'create_music'



urlpatterns = [
    path('', CreateMusicView.as_view(), name='create_music'),
    path('list/', WorkingMusicListView.as_view(), name='working_music_list'),
    path('list/<int:working_music_id>/delete/', WorkingMusicDeleteView.as_view(), name='working_music_delete'),
    path('list/<int:working_music_id>/', WorkingMusicRetrieveTemplateView.as_view(), name='working_music_detail'),
    path('list/WorkingMusicRetrieveAPI/<int:working_music_id>/', WorkingMusicRetrieveView.as_view(), name='working_music_detail_api'),
    path('list/<int:working_music_id>/SubMusicCreate', SubMusicCreateView.as_view(), name='sub_music_create'),
    path('list/<int:working_music_id>/LoopStaion', LoopStationView.as_view(), name='loopstaion'),
    path('list/<int:working_music_id>/MusicUpdate', SubMusicMergeView.as_view(), name='music_update'),
    path('list/<int:working_music_id>/SubMusicDelete', SubMusicDeleteView.as_view(), name='submusic_delete'),
    path('list/<int:working_music_id>/MusicStatusUpdate', MusicStatusChangeView.as_view(), name='music_status_change'),
    path('list/<int:working_music_id>/VoiceToPiano', VoiceToPianoView.as_view(), name='voice_to_piano'),
    path('list/<int:working_music_id>/VoiceToDrum', VoiceToDrumView.as_view(), name='voice_to_drum'),
    path('list/<int:working_music_id>/CheckStatus', MusicConvertCheckView.as_view(), name='convert_check_status'),
    path('list/<int:working_music_id>/CompleteMusic', MusicCompletedView.as_view(), name='complete_music'),
]

createmusic/models.py
from django.db import models

# Create your models here.

music/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.urls import reverse

from StackOfMusic import settings
from accounts.models import User


# class CustomFileField(models.FileField):
#     attr_class = FieldFile
#     interval = 0
#
#     def pre_save(self, model_instance, add):
#         file = super().pre_save(model_instance, add)
#         if file and not file._committed:
#             file.save(file.name, file.file, save=False)
#         return file
#
#     def set_interval(self, interval):
#         self.interval = interval


private_storage = FileSystemStorage(location=settings.STATIC_URL + settings.STATICFILES_LOCATION + '/')


class Genre(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name


class Music(models.Model):
    genre = models.ForeignKey('music.Genre', on_delete=models.CASCADE, related_name='music')
    owner = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='music_owner')
    title = models.CharField(max_length=30)
    album_jacket = models.ImageField(blank=True, upload_to='img')
    seed_file = models.FileField(upload_to='audiofile')
    completed_music = models.FileField(upload_to='audiofile', blank=True, null=True)
    instrument = models.ForeignKey('instrument.Instrument', on_delete=models.CASCADE, related_name='music', blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    liked_music = models.ManyToManyField('accounts.User', blank=True, related_name='music')
    participants = models.IntegerField(default=0)
    MUSIC_COMPLETED, MUSIC_NOT_COMPLETED = 0, 1
    MUSIC_OPTION = (
        (MUSIC_COMPLETED, '완성'),
        (MUSIC_NOT_COMPLETED, '미완성')
    )
    music_option = models.SmallIntegerField(choices=MUSIC_OPTION)
    BEFORE_UPDATE, UPDATING, AFTER_UPDATE = 0, 1, 2
    UPDATE_STATUS = (
        (BEFORE_UPDATE, '업데이트 전'),
        (UPDATING, '업데이트 중'),
        (AFTER_UPDATE, '업데이트 후'),
    )
    update_status = models.SmallIntegerField(choices=UPDATE_STATUS)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('create_music:working_music_detail', args=(self.pk,))

    @property
    def total_likes_user(self):
        return self.liked_music.count()

    def is_complete(self):
        return self.music_option == Music.MUSIC_COMPLETED

    def is_not_complete(self):
        return self.music_option == Music.MUSIC_NOT_COMPLETED


class SubMusic(models.Model):
    music = models.ForeignKey('music.Music', on_delete=models.CASCADE, related_name='sub_musics')
    contributor = models.ForeignKey('accounts.User', related_name='sub_music', on_delete=models.CASCADE)
    instrument = models.ForeignKey('instrument.Instrument', on_delete=models.CASCADE, related_name='sub_music')
    music_file = models.FileField(upload_to='audiofile')
    convert_music_file = models.FileField(upload_to=private_storage)
    create_date = models.DateTimeField(auto_now_add=True)
    ACCEPT, PENDING = 0, 1
    STATUS = (
        (ACCEPT, '머지'),
        (PENDING, '대기'),
    )
    status = models.SmallIntegerField(choices=STATUS)
    BEFORE_UPDATE, UPDATING, AFTER_UPDATE = 0, 1, 2
    UPDATE_STATUS = (
        (BEFORE_UPDATE, '업데이트 전'),
        (UPDATING, '업데이트 중'),
        (AFTER_UPDATE, '업데이트 후'),
    )
    update_status = models.SmallIntegerField(choices=UPDATE_STATUS)


class Comment(models.Model):
    music = models.ForeignKey('music.Music', on_delete=models.CASCADE, related_name='comment')
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='comment')
    comment_text = models.TextField()

    def __str__(self):
        return self.comment_text
# Music.objects.prefetch_related('sub_musics').filter(instrument_id__in=[], sub_musics__instrument_id__in=[])
# class CompletedMusic(models.Model):

createmusic/forms.py
from django import forms
from music.models import Music, Genre, SubMusic
from instrument.models import Instrument


class CreateMusicForm(forms.ModelForm):

    class Meta:
        model = Music
        fields = (
            'genre',
            'title',
            'album_jacket',
            'seed_file',
            'instrument',
        )

    def __init__(self, music_owner, *args, **kwargs):
        self.owner = music_owner
        super(CreateMusicForm, self).__init__(*args, **kwargs)
        self.fields['genre'].queryset = Genre.objects.all()
        self.fields['instrument'].queryset = Instrument.objects.all()

    def save(self, commit=True):
        self.instance.owner = self.owner
        self.instance.music_option = 1
        self.instance.update_status = 0
        return super(CreateMusicForm, self).save(commit=commit)


class CreateSubMusicForm(forms.ModelForm):

    class Meta:
        model = SubMusic
        fields = (
            'instrument',
            'music_file',
            'convert_music_file',
        )

    def __init__(self, music_contributor, working_music_id, *args, **kwargs):
        self.contributor = music_contributor
        self.music = working_music_id
        super(CreateSubMusicForm, self).__init__(*args, **kwargs)
        self.fields['instrument'].queryset = Instrument.objects.all()
        self.fields['convert_music_file'].required = False

    def save(self, commit=True):
        self.instance.contributor = self.contributor
        self.instance.music_id = self.music
        self.instance.status = 1
        self.instance.update_status = 0
        return super(CreateSubMusicForm, self).save(commit=commit)

createmusic/templates/createmusic/create_music.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

    <style>
        input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
            background-color: #39ace7;
        }

        input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        input[type=text] {
            background-color: #e9ecf0;
            border: none;
            color: #0d0d0d;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 5px;
            width: 70%;
            border: 2px solid #f6f6f6;
            -webkit-transition: all 0.5s ease-in-out;
            -moz-transition: all 0.5s ease-in-out;
            -ms-transition: all 0.5s ease-in-out;
            -o-transition: all 0.5s ease-in-out;
            transition: all 0.5s ease-in-out;
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
        }
        input[type=file] {
            background-color: #e9ecf0;
            display: inline-block;
            border: none;
            color: #0d0d0d;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 5px;
            width: 70%;
            border: 2px solid #f6f6f6;
            -webkit-transition: all 0.5s ease-in-out;
            -moz-transition: all 0.5s ease-in-out;
            -ms-transition: all 0.5s ease-in-out;
            -o-transition: all 0.5s ease-in-out;
            transition: all 0.5s ease-in-out;
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
        }
        /* FORM TYPOGRAPHY*/
        button[type=submit]{
            background-color: #56baed;
            border: none;
            color: white;
            padding: 15px 80px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            text-transform: uppercase;
            font-size: 13px;
            -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
            margin: 5px 20px 40px 20px;
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -ms-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }
        input[type=button], input[type=submit], input[type=reset]  {
            background-color: #56baed;
            border: none;
            color: white;
            padding: 15px 30px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            text-transform: uppercase;
            font-size: 13px;

        }

        input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
            background-color: #39ace7;
        }
        input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        input[type=text]:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }


        .divider-text {
            position: relative;
            text-align: center;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .divider-text span {
            padding: 7px;
            font-size: 12px;
            position: relative;
            z-index: 2;
        }
        .divider-text:after {
            content: "";
            position: absolute;
            width: 100%;
            border-bottom: 1px solid #ddd;
            top: 55%;
            left: 0;
            z-index: 1;
        }

        .btn-facebook {
            background-color: #405D9D;
            color: #fff;
        }
        .btn-twitter {
            background-color: #42AEEC;
            color: #fff;
        }



        .file_input_textbox
        {
            float: left
        }

        .file_input_hidden
        {
            width: 10px;
            font-size: 45px;
            position: absolute;
            right: 0px;
            top: 0px;
            opacity: 0;
        }
    </style>

</head>
<body style="background-color: #2e353d">






<div class="card bg-light" style="height: 100%;display: inline;background-color: #6c757d">
    <article class="card-body mx-auto" style="max-width: 400px;margin-top: 140px;background-color: whitesmoke;border-radius: 30px">
        <h4 class="card-title mt-3 text-center">Create Music</h4>
        <p class="text-center">Get started with your Talent!</p>
        <p class="divider-text">
            <span class="bg-light"></span>
        </p>
        <br>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group input-group">
                <label for="id_genre">Genre:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <select name="genre" required id="id_genre" class="form-control">
                    {% for genre in form.genre.field.queryset %}
                        <option value="{{ genre.pk }}" selected >{{ genre.name }}</option>
                    {% endfor %}
                </select>
            </div> <!-- form-group// -->
            <div class="form-group input-group">
                <label for="id_instrument">Instrument:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <select name="instrument" required id="id_instrument" class="form-control">
                    {% for instrument in form.instrument.field.queryset %}
                        <option value="{{ instrument.pk }}" selected>{{ instrument }}</option>
                    {% endfor %}
                </select>
            </div> <!-- form-group end.// -->
            <div class="form-group input-group">

                <label for="id_title">Title :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="text" name="title" maxlength="30" required id="id_title">
            </div> <!-- form-group// -->


            <div class="form-group input-group">
                <label for="id_album_jacket"style="float: left">Albumjacket:&nbsp;</label>
                <input type="text" id="fileName" class="file_input_textbox" style="float: left" readonly="readonly">
                <input type="file" class="file_input_hidden"  name="album_jacket" accept="image/*" id="id_album_jacket" onchange="javascript: document.getElementById('fileName').value = this.value" />

            </div> <!-- form-group// -->

            <div class="form-group input-group">
                <label for="id_seed_file">Seedfile :&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                <input type="text" id="fileName2" class="file_input_textbox" style="float: left" readonly="readonly">
                <input type="file" class="file_input_hidden" name="seed_file" required id="id_seed_file" onchange="javascript: document.getElementById('fileName2').value = this.value" />
            </div> <!-- form-group// -->

            <center>
                <button type="submit">만들기</button>
            </center>
        </form>

    </article>
    <br>
    <br>
</div> <!-- card.// -->

</div>
<!--container end.//-->

</body>
</html>

createmusic/templates/createmusic/create_submusic.html
{% extends 'StackOfMusic/base.html' %}

{% block content %}


    <!doctype html>
    <html lang="ko">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport"
              content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <title>Document</title>
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

        <style>
            input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
                background-color: #39ace7;
            }

            input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
                -moz-transform: scale(0.95);
                -webkit-transform: scale(0.95);
                -o-transform: scale(0.95);
                -ms-transform: scale(0.95);
                transform: scale(0.95);
            }

            input[type=text] {
                background-color: #e9ecf0;
                border: none;
                color: #0d0d0d;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 5px;
                width: 70%;
                border: 2px solid #f6f6f6;
                -webkit-transition: all 0.5s ease-in-out;
                -moz-transition: all 0.5s ease-in-out;
                -ms-transition: all 0.5s ease-in-out;
                -o-transition: all 0.5s ease-in-out;
                transition: all 0.5s ease-in-out;
                -webkit-border-radius: 5px 5px 5px 5px;
                border-radius: 5px 5px 5px 5px;
            }
            input[type=file] {
                background-color: #e9ecf0;
                display: inline-block;
                border: none;
                color: #0d0d0d;
                padding: 15px 32px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                font-size: 16px;
                margin: 5px;
                width: 70%;
                border: 2px solid #f6f6f6;
                -webkit-transition: all 0.5s ease-in-out;
                -moz-transition: all 0.5s ease-in-out;
                -ms-transition: all 0.5s ease-in-out;
                -o-transition: all 0.5s ease-in-out;
                transition: all 0.5s ease-in-out;
                -webkit-border-radius: 5px 5px 5px 5px;
                border-radius: 5px 5px 5px 5px;
            }
            /* FORM TYPOGRAPHY*/
            button[type=submit]{
                background-color: #56baed;
                border: none;
                color: white;
                padding: 15px 80px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                text-transform: uppercase;
                font-size: 13px;
                -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
                box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
                -webkit-border-radius: 5px 5px 5px 5px;
                border-radius: 5px 5px 5px 5px;
                margin: 5px 20px 40px 20px;
                -webkit-transition: all 0.3s ease-in-out;
                -moz-transition: all 0.3s ease-in-out;
                -ms-transition: all 0.3s ease-in-out;
                -o-transition: all 0.3s ease-in-out;
                transition: all 0.3s ease-in-out;
            }
            input[type=button], input[type=submit], input[type=reset]  {
                background-color: #56baed;
                border: none;
                color: white;
                padding: 15px 30px;
                text-align: center;
                text-decoration: none;
                display: inline-block;
                text-transform: uppercase;
                font-size: 13px;

            }

            input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
                background-color: #39ace7;
            }
            input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
                -moz-transform: scale(0.95);
                -webkit-transform: scale(0.95);
                -o-transform: scale(0.95);
                -ms-transform: scale(0.95);
                transform: scale(0.95);
            }

            input[type=text]:focus {
                background-color: #fff;
                border-bottom: 2px solid #5fbae9;
            }


            .divider-text {
                position: relative;
                text-align: center;
                margin-top: 15px;
                margin-bottom: 15px;
            }
            .divider-text span {
                padding: 7px;
                font-size: 12px;
                position: relative;
                z-index: 2;
            }
            .divider-text:after {
                content: "";
                position: absolute;
                width: 100%;
                border-bottom: 1px solid #ddd;
                top: 55%;
                left: 0;
                z-index: 1;
            }

            .btn-facebook {
                background-color: #405D9D;
                color: #fff;
            }
            .btn-twitter {
                background-color: #42AEEC;
                color: #fff;
            }



            .file_input_textbox
            {
                float: left
            }

            .file_input_hidden
            {
                width: 10px;
                font-size: 45px;
                position: absolute;
                right: 0px;
                top: 0px;
                opacity: 0;
            }
        </style>

    </head>

    <body style="background-color: #2e353d">
    <br>

    <div class="card bg-light" style="height: 100%;display: inline;">
        <br><br>
        <article class="card-body mx-auto" style="max-width: 400px;background-color: whitesmoke;border-radius: 20px;">
            <h4 class="card-title mt-3 text-center">Create SUB_Music</h4>
            <p class="text-center">Get started with your Talent!</p>
            <p class="divider-text">
                <span class="bg-light"></span>
            </p>
            <br>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group input-group">
                    <label for="id_instrument">Instrument:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</label>
                    <select name="instrument" required id="id_instrument" class="form-control">
                        {% for instrument in form.instrument.field.queryset %}
                            <option value="{{ instrument.id }}">{{ instrument.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="form-group input-group">
                    <label for="id_music_file">Music file:&emsp;&nbsp;&nbsp;</label>
                    <input type="text" id="fileName" class="file_input_textbox" style="float: left" readonly="readonly">
                    <input type="file" class="file_input_hidden"  name="music_file" id="id_music_file" onchange="javascript: document.getElementById('fileName').value = this.value" />

                </div>

                <center>
                    <button type="submit">만들기</button>
                </center>
            </form>

        </article>
        <br>
        <br>
    </div> <!-- card.// -->

    </div>
    <!--container end.//-->

    </body>
{% endblock %}
</html>

createmusic/templates/createmusic/loopstation.html
{% extends 'StackOfMusic/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SOM</title>
</head>
{% block extra_scripts %}

{% endblock %}
{% block content %}
    <body style="background-color: black">
    <div class="panel">
        <br>
        <img id="music_image" src="" alt="" style="height:250px;width: 250px;float: left">
        {{ sub_musics }}
        <div class="row user-left-part">
            <div class="col-md-9 col-sm-9 col-xs-12 pull-right profile-right-section" style="height: 300px;">
                <div class="row profile-right-section-row">
                    <div class="col-md-12 profile-header">
                        <div class="row">
                            <div class="col-md-8 col-sm-6 col-xs-6 profile-header-section1 pull-left">
                                <h1><div id="mytitle" style="float: left;"></div></h1>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="row">
                            <div class="col-md-8">
                                <!-- Tab panes -->
                                <div class="tab-content">
                                    <div role="tabpanel" class="tab-pane fade show active" id="profile">
                                        <div class="row">
                                            <div class="col-md-4">
                                                <label>genre</label>
                                            </div>
                                            <div class="col-md-4">
                                                <h4><div id="mygenre" style="float: left;margin-left: 20px;"></div></h4>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <label>Owner</label>
                                            </div>
                                            <div class="col-md-4">
                                                <h4><div id="myowner" style="float: left;margin-left: 20px;"></div></h4>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-4">
                                                <label>발매날짜</label>
                                            </div>
                                            <div class="col-md-4">
                                                <div id="mydate" style="float: left;margin-left: 20px;"></div>
                                            </div>
                                        </div>
                                        <audio id="music" controls style="margin-top:20px;margin-left: 10px;">
                                            <source id="audio-source" src="" type="audio/mp4"/>
                                        </audio>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {#                                <div class="container">#}
                    {#                                    <div class="post-comments">#}
                    {#                                        <form>#}
                    {#                                            <div class="form-group">#}
                    {#                                                <label for="comment">Your Comment</label>#}
                    {#                                                <textarea name="comment" class="form-control" rows="3"></textarea>#}
                    {#                                            </div>#}
                    {#                                            <button type="submit" class="btn btn-default">Send</button>#}
                    {#                                        </form>#}
                    {#                                    </div>#}
                    <!-- post-comments -->
                </div>
            </div>
        </div>

    </div>
    </body>
{% endblock %}
</html>

createmusic/templates/createmusic/working_music_delete.html
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm">
</form>