StackOfMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, CompletedMusicRetrieveView, CompletedMusicDetailTemplateView, LikeMusicAPIView, \
    LikeMusicUpdateAPI, CreateCommentView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('<int:completed_music_id>/', CompletedMusicDetailTemplateView.as_view(), name='completed_music_detail'),
    path('RetrieveAPI/<int:completed_music_id>/', CompletedMusicRetrieveView.as_view(), name='completed_music_detail_api'),
    path('LikeMusicAPI/<int:completed_music_id>', LikeMusicAPIView.as_view(), name='like_music_api'),
    path('LikeMusicUpdateAPI/<int:pk>', LikeMusicUpdateAPI, name='like_music_update'),
    path('<int:completed_music_id>/CreateComment', CreateCommentView.as_view(), name='create_comment'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('create/', include('createmusic.urls', namespace='create_music')),
    path('instrument/search/', include('instrument.urls', namespace='instrument_search')),
    path('s3direct/', include('s3direct.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import CreateUserView, CreateUserDoneView, UserLoginView, UserLogoutView, UserDetailView, \
    CopyrightTemplateView, UserWorkingProjects, MyPageListTemplateView, UserWorkingProjectsListView, \
    UserLikedMusicListView

app_name = 'accounts'


urlpatterns = [
    path('create/', CreateUserView.as_view(), name='accounts_create'),
    path('create/done', CreateUserDoneView.as_view(), name='accounts_create_done'),
    path('signin/', UserLoginView.as_view(), name='accounts_login'),
    path('signout/', UserLogoutView.as_view(url='http://localhost:8000'), name='accounts_logout'),
    path('mypage/<int:account_id>/myinfo', UserDetailView.as_view(), name='accounts_detail'),
    path('mypage/<int:account_id>/copyright/', CopyrightTemplateView.as_view(), name='accounts_copyright'),
    path('mypage/<int:account_id>/myworkingmusic/', UserWorkingProjectsListView.as_view(), name='accounts_working_projects'),
    path('mypage/<int:account_id>', MyPageListTemplateView.as_view(), name='account_list'),
    path('mypage/<int:account_id>/LkeMusic', UserLikedMusicListView.as_view(), name='user_liked_music'),
]

createmusic/urls.py
from django.urls import path

from .views import CreateMusicView, WorkingMusicListView, WorkingMusicDeleteView, WorkingMusicRetrieveView, \
    WorkingMusicRetrieveTemplateView, SubMusicMergeView, SubMusicCreateView, MusicStatusChangeView, SubMusicDeleteView, \
    VoiceToDrumView, VoiceToPianoView, LoopStationView, MusicConvertCheckView, MusicCompletedView


app_name = 'create_music'



urlpatterns = [
    path('', CreateMusicView.as_view(), name='create_music'),
    path('list/', WorkingMusicListView.as_view(), name='working_music_list'),
    path('list/<int:working_music_id>/delete/', WorkingMusicDeleteView.as_view(), name='working_music_delete'),
    path('list/<int:working_music_id>/', WorkingMusicRetrieveTemplateView.as_view(), name='working_music_detail'),
    path('list/WorkingMusicRetrieveAPI/<int:working_music_id>/', WorkingMusicRetrieveView.as_view(), name='working_music_detail_api'),
    path('list/<int:working_music_id>/SubMusicCreate', SubMusicCreateView.as_view(), name='sub_music_create'),
    path('list/<int:working_music_id>/LoopStaion', LoopStationView.as_view(), name='loopstaion'),
    path('list/<int:working_music_id>/MusicUpdate', SubMusicMergeView.as_view(), name='music_update'),
    path('list/<int:working_music_id>/SubMusicDelete', SubMusicDeleteView.as_view(), name='submusic_delete'),
    path('list/<int:working_music_id>/MusicStatusUpdate', MusicStatusChangeView.as_view(), name='music_status_change'),
    path('list/<int:working_music_id>/VoiceToPiano', VoiceToPianoView.as_view(), name='voice_to_piano'),
    path('list/<int:working_music_id>/VoiceToDrum', VoiceToDrumView.as_view(), name='voice_to_drum'),
    path('list/<int:working_music_id>/CheckStatus', MusicConvertCheckView.as_view(), name='convert_check_status'),
    path('list/<int:working_music_id>/CompleteMusic', MusicCompletedView.as_view(), name='complete_music'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from StackOfMusic import settings


class Copyright(models.Model):
    profit = models.IntegerField(default=0)
    user = models.OneToOneField('accounts.User', on_delete=models.CASCADE, related_name='copyright')
    pub_date = models.DateTimeField(auto_now_add=True)


class User(AbstractUser):
    GENDER_MAIL, GENDER_FEMAIL = 0, 1
    GENDER_OPTION = (
        (GENDER_MAIL, '남성'),
        (GENDER_FEMAIL, '여성'),
    )
    sex = models.SmallIntegerField(choices=GENDER_OPTION, null=True)
    age = models.IntegerField(default=0)
    bank_account_number = models.CharField(max_length=15, null=True)
    bank = models.ForeignKey('bank.Bank', on_delete=models.CASCADE, related_name='user', null=True)

    class Meta:
        swappable = settings.AUTH_USER_MODEL

accounts/forms.py
from django import forms
from django.db import models
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import User
from bank.models import Bank


class CreateUserForm(UserCreationForm):
    bank = forms.ModelChoiceField(queryset=None, empty_label='---------')

    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
            'sex',
            'age',
            'bank_account_number',
        )

    def __init__(self, *args, **kwargs):
        super(CreateUserForm, self).__init__(*args, **kwargs)
        self.fields['bank'].queryset = Bank.objects.all()


class UserAuthenticationForm(AuthenticationForm):
    error_messages = '비밀번호가 틀렸습니다.'

accounts/views.py
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView, TemplateView, RedirectView, DetailView, FormView, ListView
from rest_framework import mixins, generics

from accounts.models import Copyright
from music.models import Music
from .forms import CreateUserForm
from .models import User
from .serializer import CopyrightSerializer, UserWorkingProjectsSerializer


class CreateUserView(CreateView):
    template_name = 'accounts/create_user.html'
    form_class = CreateUserForm
    success_url = reverse_lazy('accounts:accounts_create_done')


class CreateUserDoneView(TemplateView):
    template_name = 'accounts/create_user_done.html'


class UserLoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('home')

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        request.session.set_test_cookie()

        return super(UserLoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(UserLoginView, self).form_valid(form)

    def get_success_url(self):
        return super(UserLoginView, self).get_success_url()


class UserLogoutView(RedirectView):
    url = reverse_lazy('home')

    @method_decorator(never_cache)
    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(UserLogoutView, self).get(request, *args, **kwargs)


class UserDetailView(DetailView):
    template_name = 'accounts/mypage.html'
    model = User
    pk_url_kwarg = 'account_id'

    def get_context_data(self, **kwargs):
        context = super(UserDetailView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        context['user_music_list'] = self.request.user.music_owner.all()
        # context['user_contrib_music_list'] = self.request.user.music_contributor.all()
        return context


class CopyrightAPIView(mixins.ListModelMixin, generics.GenericAPIView):
    object = Copyright.objects.all()
    serializer_class = CopyrightSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class CopyrightTemplateView(TemplateView):
    template_name = 'accounts/copyright.html'

    def get_context_data(self, **kwargs):
        context = super(CopyrightTemplateView, self).get_context_data(**kwargs)
        context['user'] = self.request.user
        return context


class UserWorkingProjects(mixins.ListModelMixin, generics.GenericAPIView):

    serializer_class = UserWorkingProjectsSerializer

    def get_queryset(self):
        queryset = Music.objects.filter(owner=self.request.user, contributor=self.request.user)
        return queryset

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)


class UserWorkingProjectsListView(ListView):
    template_name = 'accounts/user_working_projects.html'
    model = Music
    pk_url_kwarg = 'account_id'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(UserWorkingProjectsListView, self).get_context_data(object_list=None, **kwargs)
        context['working_music_list'] = self.request.user.music_owner.all()
        return context


class MyPageListTemplateView(TemplateView):
    template_name = 'accounts/mypage_list.html'

    def get_context_data(self, **kwargs):
        context = super(MyPageListTemplateView, self).get_context_data(**kwargs)
        context['account_id'] = self.request.user.id
        return context


class UserLikedMusicListView(ListView):
    template_name = 'accounts/user_liked_music.html'
    model = Music
    context_object_name = 'user_liked_music_list'
    pk_url_kwarg = 'account_id'

    def get(self, request, *args, **kwargs):
        return super(UserLikedMusicListView, self).get(request, *args, **kwargs)

    def get_queryset(self):
        user_id = self.request.user.id
        queryset = User.objects.get(id=user_id).music.all()
        return queryset

accounts/templates/accounts/create_user.html
<!doctype html>
<html lang="ko">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.8/css/all.css">

<!------ Include the above in your HEAD tag ---------->

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>회원가입</title>

    <style>
        .divider-text {
            position: relative;
            text-align: center;
            margin-top: 15px;
            margin-bottom: 15px;
        }
        .divider-text span {
            padding: 7px;
            font-size: 12px;
            position: relative;
            z-index: 2;
        }
        .divider-text:after {
            content: "";
            position: absolute;
            width: 100%;
            border-bottom: 1px solid #ddd;
            top: 55%;
            left: 0;
            z-index: 1;
        }

        .btn-facebook {
            background-color: #405D9D;
            color: #fff;
        }
        .btn-twitter {
            background-color: #42AEEC;
            color: #fff;
        }
    </style>

</head>
<body>

<div class="card bg-light">
    <article class="card-body mx-auto" style="max-width: 400px;">
        <h4 class="card-title mt-3 text-center">Create Account</h4>
        <p class="text-center">Get started with your free account</p>
        <p class="divider-text">
            <span class="bg-light"></span>
        </p>
        <br>
        <form method="post" action="{% url 'accounts:accounts_create' %}">
            {% csrf_token %}
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-user"></i> </span>
                </div>
                <input placeholder="Username" class="form-control" type="text" name="username" maxlength="150" autofocus required id="id_username">
            </div> <!-- form-group// -->
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-minus-square"></i> </span>
                </div>
                <input placeholder="First name" class="form-control" type="text" name="first_name" maxlength="30" id="id_first_name">
            </div> <!-- form-group// -->

            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-info-circle"></i> </span>
                </div>
                <input placeholder="Last name" class="form-control" type="text" name="last_name" maxlength="150" id="id_last_name">
            </div> <!-- form-group// -->

            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-envelope"></i> </span>
                </div>
                <input placeholder="Email address" class="form-control" type="email" name="email" maxlength="254" id="id_email">
            </div> <!-- form-group// -->
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-building"></i> </span>
                </div>
                <select class="form-control" name="sex" required id ="id_sex">
                    {% for male,female in form.fields.sex.choices %}
                        <option value="{{ male }}"{% if form.fields.sex.value == male %} selected{% endif %}>{{ female }}</option>
                    {% endfor %}
                </select>
            </div> <!-- form-group end.// -->
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-check-circle"></i> </span>
                </div>
                <input placeholder="Age" class="form-control" type="number" name="age" required id="id_age">
            </div> <!-- form-group// -->
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-building"></i> </span>
                </div>
                <input type="text" placeholder="Bank account number" class="form-control" name="bank_account_number" maxlength="15" required id="id_bank_account_number">
            </div> <!-- form-group// -->

            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-building"></i> </span>
                </div>
                <select class="form-control" name="bank" required id="id_bank">
                    {% for z in form.bank.field.queryset %}
                        <option value="{{ z.pk }}" selected >{{ z.name }}</option>
                    {% endfor %}
                </select>
            </div> <!-- form-group end.// -->


            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                <input placeholder="Password" class="form-control" type="password" name="password1" required id="id_password1"> <span class="helptext"></span>

            </div> <!-- form-group// -->
            <div class="form-group input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text"> <i class="fa fa-lock"></i> </span>
                </div>
                <input class="form-control" placeholder="Repeat password" type="password" name="password2" required id="id_password2"> <span class="helptext"></span>

            </div> <!-- form-group// -->
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block"> Create Account  </button>
            </div> <!-- form-group// -->
            {{ field.errors.as_ul }}
            {{ field }}
        </form>

        <p class="text-center">Have an account? <a href="{% url 'accounts:accounts_login' %}">Log In</a> </p>
    </article>
<br>
<br>
</div> <!-- card.// -->

</div>
<!--container end.//-->

</body>
</html>

accounts/templates/accounts/create_user_done.html
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>SOM</title>
    <style>

        /* BASIC */


        body {
            font-family: "Poppins", sans-serif;
            height: 100vh;
        }

        a {
            color: #92badd;
            display:inline-block;
            text-decoration: none;
            font-weight: 400;
        }

        h2 {
            text-align: center;
            font-size: 16px;
            font-weight: 600;
            text-transform: uppercase;
            display:inline-block;
            margin: 40px 8px 10px 8px;
            color: #cccccc;
        }



        /* STRUCTURE */

        .wrapper {
            display: flex;
            align-items: center;
            flex-direction: column;
            justify-content: center;
            width: 100%;
            min-height: 100%;
            padding: 20px;
        }

        #formContent {
            -webkit-border-radius: 10px 10px 10px 10px;
            border-radius: 10px 10px 10px 10px;
            background: #fff;
            padding: 30px;
            width: 90%;
            max-width: 450px;
            position: relative;
            padding: 0px;
            -webkit-box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
            box-shadow: 0 30px 60px 0 rgba(0,0,0,0.3);
            text-align: center;
        }

        #formFooter {
            background-color: #f6f6f6;
            border-top: 1px solid #dce8f1;
            padding: 25px;
            text-align: center;
            -webkit-border-radius: 0 0 10px 10px;
            border-radius: 0 0 10px 10px;
        }



        /* TABS */

        h2.inactive {
            color: #cccccc;
        }

        h2.active {
            color: #0d0d0d;
            border-bottom: 2px solid #5fbae9;
        }



        /* FORM TYPOGRAPHY*/
        button[type=submit]{
            background-color: #56baed;
            border: none;
            color: white;
            padding: 15px 80px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            text-transform: uppercase;
            font-size: 13px;
            -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
            margin: 5px 20px 40px 20px;
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -ms-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }
        input[type=button], input[type=submit], input[type=reset]  {
            background-color: #56baed;
            border: none;
            color: white;
            padding: 15px 80px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            text-transform: uppercase;
            font-size: 13px;
            -webkit-box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            box-shadow: 0 10px 30px 0 rgba(95,186,233,0.4);
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
            margin: 5px 20px 40px 20px;
            -webkit-transition: all 0.3s ease-in-out;
            -moz-transition: all 0.3s ease-in-out;
            -ms-transition: all 0.3s ease-in-out;
            -o-transition: all 0.3s ease-in-out;
            transition: all 0.3s ease-in-out;
        }

        input[type=button]:hover, input[type=submit]:hover, input[type=reset]:hover  {
            background-color: #39ace7;
        }

        input[type=button]:active, input[type=submit]:active, input[type=reset]:active  {
            -moz-transform: scale(0.95);
            -webkit-transform: scale(0.95);
            -o-transform: scale(0.95);
            -ms-transform: scale(0.95);
            transform: scale(0.95);
        }

        input[type=text] {
            background-color: #f6f6f6;
            border: none;
            color: #0d0d0d;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 5px;
            width: 85%;
            border: 2px solid #f6f6f6;
            -webkit-transition: all 0.5s ease-in-out;
            -moz-transition: all 0.5s ease-in-out;
            -ms-transition: all 0.5s ease-in-out;
            -o-transition: all 0.5s ease-in-out;
            transition: all 0.5s ease-in-out;
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
        }

        input[type=text]:focus {
            background-color: #fff;
            border-bottom: 2px solid #5fbae9;
        }

        input[type=text]::placeholder {
            color: #cccccc;
        }

        input[type=password] {
            background-color: #f6f6f6;
            border: none;
            color: #0d0d0d;
            padding: 15px 32px;
            text-align: center;
            text-decoration: none;
            display: inline-block;
            font-size: 16px;
            margin: 5px;
            width: 85%;
            border: 2px solid #f6f6f6;
            -webkit-transition: all 0.5s ease-in-out;
            -moz-transition: all 0.5s ease-in-out;
            -ms-transition: all 0.5s ease-in-out;
            -o-transition: all 0.5s ease-in-out;
            transition: all 0.5s ease-in-out;
            -webkit-border-radius: 5px 5px 5px 5px;
            border-radius: 5px 5px 5px 5px;
        }




        /* ANIMATIONS */

        /* Simple CSS3 Fade-in-down Animation */
        .fadeInDown {
            -webkit-animation-name: fadeInDown;
            animation-name: fadeInDown;
            -webkit-animation-duration: 1s;
            animation-duration: 1s;
            -webkit-animation-fill-mode: both;
            animation-fill-mode: both;
        }

        @-webkit-keyframes fadeInDown {
            0% {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
            }
            100% {
                opacity: 1;
                -webkit-transform: none;
                transform: none;
            }
        }

        @keyframes fadeInDown {
            0% {
                opacity: 0;
                -webkit-transform: translate3d(0, -100%, 0);
                transform: translate3d(0, -100%, 0);
            }
            100% {
                opacity: 1;
                -webkit-transform: none;
                transform: none;
            }
        }

        /* Simple CSS3 Fade-in Animation */
        @-webkit-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
        @-moz-keyframes fadeIn { from { opacity:0; } to { opacity:1; } }
        @keyframes fadeIn { from { opacity:0; } to { opacity:1; } }

        .fadeIn {
            opacity:0;
            -webkit-animation:fadeIn ease-in 1;
            -moz-animation:fadeIn ease-in 1;
            animation:fadeIn ease-in 1;

            -webkit-animation-fill-mode:forwards;
            -moz-animation-fill-mode:forwards;
            animation-fill-mode:forwards;

            -webkit-animation-duration:1s;
            -moz-animation-duration:1s;
            animation-duration:1s;
        }

        .fadeIn.first {
            -webkit-animation-delay: 0.4s;
            -moz-animation-delay: 0.4s;
            animation-delay: 0.4s;
        }

        .fadeIn.second {
            -webkit-animation-delay: 0.6s;
            -moz-animation-delay: 0.6s;
            animation-delay: 0.6s;
        }

        .fadeIn.third {
            -webkit-animation-delay: 0.8s;
            -moz-animation-delay: 0.8s;
            animation-delay: 0.8s;
        }

        .fadeIn.fourth {
            -webkit-animation-delay: 1s;
            -moz-animation-delay: 1s;
            animation-delay: 1s;
        }

        /* Simple CSS3 Fade-in Animation */
        .underlineHover:after {
            display: block;
            left: 0;
            bottom: -10px;
            width: 0;
            height: 2px;
            background-color: #56baed;
            content: "";
            transition: width 0.2s;
        }

        .underlineHover:hover {
            color: #0d0d0d;
        }

        .underlineHover:hover:after{
            width: 100%;
        }



        /* OTHERS */

        *:focus {
            outline: none;
        }

        #icon {
            width:60%;
        }

    </style>
</head>
<body>

<div class="wrapper fadeInDown">
    <div id="formContent">
        <!-- Tabs Titles -->

        <!-- Icon -->
        <div class="fadeIn first">
            <br>
            <img src="../../../static/img/login.png" style="width:50px" />
        </div>

        <div class="fadeIn second">
            <h1 class="site-heading text-center text-white d-none d-lg-block">
                {#    <span class="site-heading-upper">A Free Bootstrap 4 Business Theme</span>#}
                <span class="site-heading-lower  mb-3" style="color: #56baed; border-color: #fbfbff;"><b><b>회원가입 완료</b></b></span>
            </h1>
        </div>
        <!-- Login Form -->
        <button type="submit" class="fadeIn third" onclick="location.href='{% url 'accounts:accounts_login' %}'">로그인하러가기</button>

    </div>
</div>

</body>
</html>

accounts/templates/accounts/mypage_list.html
{% extends 'StackOfMusic/base.html' %}

{% block content %}
    <section style="background-color: black;height: 1000px">
        <center>
            <br>
            <button class="btn btn-lg btn-default" onclick="location.href='{% url 'accounts:accounts_copyright' account_id %}'" style="width: 1000px;font-size:70px;background-color: #2e353d;color: whitesmoke">Copyright</button>
            <br>
            <br>
            <button class="btn btn-lg btn-default" onclick="location.href='{% url 'accounts:accounts_working_projects' account_id %}'" style="width: 1000px;font-size:70px;background-color: #2e353d;color: whitesmoke">My Working Projects</button>
            <br>
            <br>
            <button class="btn btn-lg btn-default" onclick="location.href='{% url 'accounts:accounts_detail' account_id %}'" style="width: 1000px;font-size:70px;background-color: #2e353d;color: whitesmoke">My Info</button>
            <br>
            <br>
            <button class="btn btn-lg btn-default" onclick="location.href='{% url 'accounts:user_liked_music' account_id %}'" style="width: 1000px;font-size:70px;background-color: #2e353d;color: whitesmoke">Liked Music</button>

        </center>
    </section>
    {#    <a href="{% url 'accounts:accounts_copyright' account_id %}">copyright</a>#}
    {#    <br>#}
    {#    <a href="{% url 'accounts:accounts_working_projects' account_id %}">MyWorkingProjects</a>#}
    {#    <br>#}
    {#    <a href="{% url 'accounts:accounts_detail' account_id %}">My info</a>#}
    {#    <br>#}
    {#    <a href="#"></a>#}
{% endblock %}

accounts/templates/accounts/user_liked_music.html
{% extends 'StackOfMusic/base.html' %}

{% block content %}
    <section style="background-color: black;height: 700px;">

        <br><br>
        <div style="margin-left: 350px; height: 100px;float: left"></div>
        <p style="color: #f2f2f2; background: #ff4a4a; font-size: 20px; line-height: 20px; font-weight: 700; margin: 0 5px 24px; float: left; padding: 10px; margin: 0 5px 24px; font-family: 'Libre Baskerville', serif;">Liked Music</p>
        <br><br>
        <center>
            <div style="margin-left: 250px;">
                {% for user_liked_music in user_liked_music_list %}
                    <button class="my-transparent-button" onclick="location.href='{% url 'completed_music_detail' user_liked_music.id %}'" style="float: left;">
                        <a href="{% url 'completed_music_detail' user_liked_music.id %}">
                            <div class="card-body">
                                <img src="{{ user_liked_music.album_jacket.url }}">
                                <h6 class="card-title" style="color: white">{{ user_liked_music }}</h6>
                            </div>
                        </a>
                    </button>
                {% endfor %}
            </div>
        </center>
    </section>

{% endblock %}

accounts/templates/accounts/user_working_projects.html
{% extends 'StackOfMusic/base.html' %}

{% block content %}
    <section style="background-color: black;height: 700px;">
        <br><br>
        <center>
            <div style="margin-left: 250px;">
                {% for working_music in working_music_list%}
                    <button class="my-transparent-button" onclick="location.href='{% url 'create_music:working_music_detail' working_music.id %}'" style="float: left;">
                        <img class="card-img-top" id="{{ working_music.title }}" src="{{ working_music.album_jacket.url }}" alt="Card image" style="width:200px;height: 200px;">
                        <a href="{% url 'create_music:working_music_detail' working_music.id %}">
                            <div class="card-body">
                                <h6 class="card-title" style="color: white">{{ working_music }}</h6>
                            </div>
                        </a>
                    </button>
                {% endfor %}
            </div>
        </center>
    </section>

{% endblock %}