StackOfMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, CompletedMusicRetrieveView, CompletedMusicDetailTemplateView, LikeMusicAPIView, \
    LikeMusicUpdateAPI, CreateCommentView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('<int:completed_music_id>/', CompletedMusicDetailTemplateView.as_view(), name='completed_music_detail'),
    path('RetrieveAPI/<int:completed_music_id>/', CompletedMusicRetrieveView.as_view(), name='completed_music_detail_api'),
    path('LikeMusicAPI/<int:completed_music_id>', LikeMusicAPIView.as_view(), name='like_music_api'),
    path('LikeMusicUpdateAPI/<int:pk>', LikeMusicUpdateAPI, name='like_music_update'),
    path('<int:completed_music_id>/CreateComment', CreateCommentView.as_view(), name='create_comment'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('create/', include('createmusic.urls', namespace='create_music')),
    path('instrument/search/', include('instrument.urls', namespace='instrument_search')),
    path('s3direct/', include('s3direct.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import CreateUserView, CreateUserDoneView, UserLoginView, UserLogoutView, UserDetailView, \
    CopyrightTemplateView, UserWorkingProjects, MyPageListTemplateView, UserWorkingProjectsListView, \
    UserLikedMusicListView

app_name = 'accounts'


urlpatterns = [
    path('create/', CreateUserView.as_view(), name='accounts_create'),
    path('create/done', CreateUserDoneView.as_view(), name='accounts_create_done'),
    path('signin/', UserLoginView.as_view(), name='accounts_login'),
    path('signout/', UserLogoutView.as_view(url='http://localhost:8000'), name='accounts_logout'),
    path('mypage/<int:account_id>/myinfo', UserDetailView.as_view(), name='accounts_detail'),
    path('mypage/<int:account_id>/copyright/', CopyrightTemplateView.as_view(), name='accounts_copyright'),
    path('mypage/<int:account_id>/myworkingmusic/', UserWorkingProjectsListView.as_view(), name='accounts_working_projects'),
    path('mypage/<int:account_id>', MyPageListTemplateView.as_view(), name='account_list'),
    path('mypage/<int:account_id>/LkeMusic', UserLikedMusicListView.as_view(), name='user_liked_music'),
]

createmusic/urls.py
from django.urls import path

from .views import CreateMusicView, WorkingMusicListView, WorkingMusicDeleteView, WorkingMusicRetrieveView, \
    WorkingMusicRetrieveTemplateView, SubMusicMergeView, SubMusicCreateView, MusicStatusChangeView, SubMusicDeleteView, \
    VoiceToDrumView, VoiceToPianoView, LoopStationView, MusicConvertCheckView, MusicCompletedView


app_name = 'create_music'



urlpatterns = [
    path('', CreateMusicView.as_view(), name='create_music'),
    path('list/', WorkingMusicListView.as_view(), name='working_music_list'),
    path('list/<int:working_music_id>/delete/', WorkingMusicDeleteView.as_view(), name='working_music_delete'),
    path('list/<int:working_music_id>/', WorkingMusicRetrieveTemplateView.as_view(), name='working_music_detail'),
    path('list/WorkingMusicRetrieveAPI/<int:working_music_id>/', WorkingMusicRetrieveView.as_view(), name='working_music_detail_api'),
    path('list/<int:working_music_id>/SubMusicCreate', SubMusicCreateView.as_view(), name='sub_music_create'),
    path('list/<int:working_music_id>/LoopStaion', LoopStationView.as_view(), name='loopstaion'),
    path('list/<int:working_music_id>/MusicUpdate', SubMusicMergeView.as_view(), name='music_update'),
    path('list/<int:working_music_id>/SubMusicDelete', SubMusicDeleteView.as_view(), name='submusic_delete'),
    path('list/<int:working_music_id>/MusicStatusUpdate', MusicStatusChangeView.as_view(), name='music_status_change'),
    path('list/<int:working_music_id>/VoiceToPiano', VoiceToPianoView.as_view(), name='voice_to_piano'),
    path('list/<int:working_music_id>/VoiceToDrum', VoiceToDrumView.as_view(), name='voice_to_drum'),
    path('list/<int:working_music_id>/CheckStatus', MusicConvertCheckView.as_view(), name='convert_check_status'),
    path('list/<int:working_music_id>/CompleteMusic', MusicCompletedView.as_view(), name='complete_music'),
]

instrument/urls.py
from django.urls import path
from .views import MusicListView, InstrumentSearchResultListAPIView


app_name = 'instrument_search'

urlpatterns = [
    path('', MusicListView.as_view(), name='instrument_search'),
    path('api/<int:instrument_id>', InstrumentSearchResultListAPIView.as_view(), name='instrument_search_api'),
]

StackOfMusic/forms.py
from django import forms
from music.models import Comment


class CreateCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = (
            'comment_text',
        )

    def __init__(self, user, music, *args, **kwargs):
        self.user = user
        self.music = music
        super(CreateCommentForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        self.instance.user = self.user
        self.instance.music = self.music
        return super(CreateCommentForm, self).save(commit=commit)

StackOfMusic/views.py
from django.db.models import Count
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import BaseCreateView
from rest_framework import mixins, generics, permissions
from rest_framework.authentication import SessionAuthentication, \
    BasicAuthentication

from StackOfMusic.forms import CreateCommentForm
from accounts.models import User
from music.models import Music, Comment
from .serializer import CompletedMusicSerializer, LikeMusicSerializer

login_url = reverse_lazy('accounts:accounts_login')


class HomeView(ListView):
    template_name = 'StackOfMusic/home.html'
    model = Music
    context_object_name = 'completed_music_list'

    def get_queryset(self):
        queryset = self.model.objects.filter(music_option=Music.MUSIC_COMPLETED).order_by('-create_date')[:5]
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(HomeView, self).get_context_data(object_list=None, **kwargs)
        context['hot_music_list'] = Music.objects.filter(music_option=0) \
            .annotate(liked_count=Count('liked_music')) \
            .order_by('-liked_count')
        return context


class CompletedMusicDetailView(DetailView):
    template_name = 'StackOfMusic/music_detail.html'
    model = Music
    pk_url_kwarg = 'completed_music_id'

    def get_queryset(self):
        queryset = super(CompletedMusicDetailView, self).get_queryset()
        completed_music_id = self.kwargs.get('completed_music_id')
        return queryset.filter(id=completed_music_id)

    def get_context_data(self, **kwargs):
        context = super(CompletedMusicDetailView, self).get_context_data(**kwargs)
        context['completed_music'] = Music.objects.filter(pk=self.kwargs.get('completed_music_id'))
        return context

    def render_to_response(self, context, **response_kwargs):
        super(CompletedMusicDetailView, self).render_to_response(context, **response_kwargs)
        return JsonResponse(context, **response_kwargs)


class CompletedMusicRetrieveView(mixins.RetrieveModelMixin, generics.GenericAPIView):
    lookup_url_kwarg = 'completed_music_id'
    serializer_class = CompletedMusicSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Music.objects.all()
        return queryset


class CompletedMusicDetailTemplateView(TemplateView):
    template_name = 'StackOfMusic/music_detail.html'

    def get_context_data(self, **kwargs):
        context = super(CompletedMusicDetailTemplateView, self).get_context_data(**kwargs)
        context['completed_music_id'] = self.kwargs.get('completed_music_id')
        context['user'] = User.objects.all()
        return context


# @method_decorator(login_required(login_url=login_url))
class LikeMusicAPIView(mixins.UpdateModelMixin, generics.GenericAPIView):
    authentication_classes = [SessionAuthentication, BasicAuthentication]
    serializer_class = LikeMusicSerializer
    permission_classes = [permissions.IsAuthenticated]

    def post(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def update(self, request, *args, **kwargs):
        complete_music_id = request.POST['pk']
        complete_music = get_object_or_404(Music, id=complete_music_id)
        filtered_like_music = self.request.user.liked_music.filter(id=complete_music_id)
        user = self.request.user
        if filtered_like_music.exist():
            user.liked_music.remove(complete_music)
        else:
            user.liked_music.add(complete_music)

        return super(LikeMusicAPIView, self).update(request, *args, **kwargs)


class CreateCommentView(BaseCreateView):
    model = Comment
    form_class = CreateCommentForm
    pk_url_kwarg = 'completed_music_id'

    def get_success_url(self):
        completed_music_id = self.kwargs.get(self.pk_url_kwarg)
        return reverse_lazy('completed_music_detail', kwargs={'completed_music_id': completed_music_id})

    def get_context_data(self, **kwargs):
        context = super(CreateCommentView, self).get_context_data(**kwargs)
        context['completed_music_id'] = self.kwargs.get(self.pk_url_kwarg)
        return context

    def get_form_kwargs(self):
        kwargs = super(CreateCommentView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        kwargs['music'] = get_object_or_404(Music, pk=self.kwargs.get(self.pk_url_kwarg))
        return kwargs


@csrf_exempt
def LikeMusicUpdateAPI(request, pk):
    music = get_object_or_404(Music, pk=pk)
    user = User.objects.get(username=request.user)
    if music.liked_music.filter(id=user.id).exists():
        music.liked_music.remove(user)
    else:
        music.liked_music.add(user)
    context = {'total_music_like': str(music.total_likes_user)}
    return JsonResponse(context, json_dumps_params={'ensure_ascii': True})

templates/StackOfMusic/base.html
{% load staticfiles %}

<!doctype html>
<html lang="ko" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}StackOfMusic{% endblock %}</title>
    {% block extra_style %}{% endblock %}
    {% block extra_scripts %}{% endblock %}

    <!-- Bootstrap core CSS -->
    <link href="{% static "StackOfMusic/vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "StackOfMusic/css/business-casual.css" %}" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <style>
        .my-transparent-button {
            background-color: transparent !important;
            background-image: none !important;
            border-color: transparent;
            border: none;
            color: #FFFFFF;
        }
    </style>

</head>
<body>
{#background-image: url({% static 'img/mu.jpg' %})#}
<section style="background-color: black; background-position: center; background-size: 1700px" >

    <nav class="navbar navbar-expand navbar-primary navbar-dark" style="background-color: black">
        <ul class="navbar-nav">
            {% if user.is_authenticated %}

                <a href="{% url 'accounts:accounts_detail' user.id %}"><img src="{% static 'img/login.png' %}" style="width: 40px;height: 40px;margin-left: 1670px;"></a>
                <br>
                <a href="{% url 'accounts:accounts_logout' %}"><img src="{% static 'img/logout.png' %}" style="width: 40px;height: 40px;margin-left: 20px;"></a>
                <br>
                <a href="{% url 'create_music:working_music_list' %}"><img src="{% static 'img/user.png' %}" style="width: 40px;height: 40px;margin-left: 15px;"></a>
                <br>
                {% comment %}
                {% for completed_music in completed_music_list %}
                    <li><a href="{% url 'completed_music_detail' completed_music.id %}">{{ completed_music.title }}</a>
                    </li>

                {% endfor %}
                {% endcomment%}

                </ul>
                </nav>

                <h1 class="site-heading text-center text-white d-none d-lg-block">
                    {#    <span class="site-heading-upper">A Free Bootstrap 4 Business Theme</span>#}
                    <span class="site-heading-lower  mb-3" style="color: white; border-color: #fbfbff;text-shadow: -10px 0 black, 0 1px black, 1px 0 black, 0 -1px black;"><b><b>Stack Of Music</b></b></span>
                </h1>
                <section>
                    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" style="background: linear-gradient(to right, red, purple);height: 50px" id="mainNav">
                        <div class="container">
                            <div class="collapse navbar-collapse" id="navbarResponsive">
                                <ul class="navbar-nav mx-auto">
                                    <li class="nav-item active px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href={% url 'home' %}><b>Home</b>
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;"
                                           href="{% url 'create_music:working_music_list' %}"><b>Music</b></a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href="{% url 'instrument_search:instrument_search' %}"><b>Instrument</b></a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href="{% url 'accounts:account_list' user.id %}"><b>Mypage</b></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </section>

            {% else %}

                <a href="{% url 'accounts:accounts_login' %}"><img src="{% static 'img/login.png' %}" style="width: 40px;height: 40px;margin-left: 1670px;"></a>
                <br>
                <a href="{% url 'accounts:accounts_logout' %}"><img src="{% static 'img/logout.png' %}" style="width: 40px;height: 40px;margin-left: 20px;"></a>
                <br>
                <a href="{% url 'accounts:accounts_create' %}"><img src="{% static 'img/user.png' %}" style="width: 40px;height: 40px;margin-left: 15px;"></a>
                <br>
                </ul>
                </nav>
                <h1 class="site-heading text-center text-white d-none d-lg-block">
                    {#    <span class="site-heading-upper">A Free Bootstrap 4 Business Theme</span>#}
                    <span class="site-heading-lower  mb-3" style="color: white; border-color: #fbfbff;text-shadow: -10px 0 black, 0 1px black, 1px 0 black, 0 -1px black;"><b><b>Stack Of Music</b></b></span>
                </h1>
                <section>
                    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" style="background: linear-gradient(to right, red, purple);height: 50px" id="mainNav">
                        <div class="container">
                            <div class="collapse navbar-collapse" id="navbarResponsive">
                                <ul class="navbar-nav mx-auto">
                                    <li class="nav-item active px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href={% url 'home' %}><b>Home</b>
                                            <span class="sr-only">(current)</span>
                                        </a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;"
                                           href="{% url 'create_music:working_music_list' %}"><b>Music</b></a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href="{% url 'instrument_search:instrument_search' %}"><b>Instrument</b></a>
                                    </li>
                                    <li class="nav-item px-lg-4">
                                        <a class="nav-link text-uppercase text-expanded" style="color: white;font-size: 20px;" href="{% url 'accounts:accounts_login'%}"><b>Mypage</b></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </section>
            {% endif %}
    </ul>
    </nav>
</section>





{% block content %}

{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
        integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
        crossorigin="anonymous"></script>



<!-- Bootstrap core JavaScript -->
<script src="{% static "StackOfMusic/vendor/jquery/jquery.js" %}"></script>
<script src="{% static "StackOfMusic/vendor/bootstrap/js/bootstrap.bundle.js" %}"></script>

</body>
</html>

templates/StackOfMusic/footer.html
    <footer class="footer text-faded text-center py-5">
        <div class="container">
            <p class="m-0 small">Copyright &copy; Your Website 2019</p>
        </div>
    </footer>

templates/StackOfMusic/home.html
{% extends 'StackOfMusic/base.html' %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>

    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1.0, minimum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>SOM</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static "StackOfMusic/vendor/bootstrap/css/bootstrap.css" %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static "StackOfMusic/css/business-casual.css" %}" rel="stylesheet">


    <style>
        section {
            width: 100%;

        }
        section.left {
            width: 20%;
            overflow: hidden;
            float: left;
            background-color: black;
            box-sizing: border-box;
        }
        section.right {
            width: 20%;
            float: right;
            box-sizing: border-box;
            background-color: #39ace7;
        }
    </style>



    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</head>


<body>
{% block content %}
    <section style="    background-color: black;height: 800px;">
<br>
        <div class="container" style="margin-left: 350px;">
            <div class="card" style="width:200px;background-color: white;border: none;display: inline">
                <p style=" color: #f2f2f2; background: #ff4a4a; font-size: 20px; line-height: 20px; font-weight: 700; margin: 0 5px 24px; float: left; padding: 10px; margin: 0 5px 24px; font-family: 'Libre Baskerville', serif;">Today's Musics</p>
                <br><br><br>

                {% for completed_music in completed_music_list %}
                    <button class="my-transparent-button" onclick="location.href='{% url 'completed_music_detail' completed_music.id %}'" style="float: left;">
                        <img class="card-img-top" id="{{ completed_music.title }}" src="{{ completed_music.album_jacket.url }}" alt="Card image" style="width:200px;height: 200px;">
                        <a href="{% url 'completed_music_detail' completed_music.id %}">
                            <div class="card-body">
                                <h6 class="card-title" style="color: white">{{ completed_music.title }}</h6>
                            </div>
                        </a>
                    </button>
                {% endfor %}
            </div>
            <br><br><br><br>
            <div style="height: 200px;"></div>
            <div class="card" style="width:200px;background-color: white;border: none;text-align: left;display: inline">
                <p style=" color: #f2f2f2; background: #ff4a4a; font-size: 20px; line-height: 20px; font-weight: 700; margin: 0 5px 24px; float: left; padding: 10px; margin: 0 5px 24px; font-family: 'Libre Baskerville', serif;">HOT Musics</p>
                <br><br><br>

                {% for hot_music in hot_music_list %}
                    <button class="my-transparent-button" onclick="location.href='{% url 'completed_music_detail' hot_music.id %}'" style="float: left">
                        <img class="card-img-top" id="{{ hot_music.title }}" src="{{ hot_music.album_jacket.url }}" alt="Card image" style="width:200px;height: 200px;">
                        <a href="{% url 'completed_music_detail' hot_music.id %}">
                            <div class="card-body">
                                <h6 class="card-title" style="color: white">{{ hot_music.title }}</h6>

                            </div>
                        </a>
                    </button>
                {% endfor %}

            </div>
        </div>

    </section>

    <section style="background-color: black;height: 600px;">

        <div id="demo" class="carousel slide" data-ride="carousel" style="">
            <ol class="carousel-indicators">
                <li data-target="#carousel-with-lb" data-slide-to="0" class="active secondary-color"></li>
                <li data-target="#carousel-with-lb" data-slide-to="1" class="secondary-color"></li>
                <li data-target="#carousel-with-lb" data-slide-to="2" class="secondary-color"></li>
            </ol>
            <ul class="carousel-indicators">
                <li data-target="#demo" data-slide-to="0" class="active"></li>
                <li data-target="#demo" data-slide-to="1"></li>
                <li data-target="#demo" data-slide-to="2"></li>
            </ul>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <center>
                        <img src="../../static/img/artist8.png"
                             alt="Los Angeles" width="1100" height="500">
                    </center>
                    <div class="carousel-caption">
                        <h3>Did It Again</h3>
                        <p>We had such a great time</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <center>
                        <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(4).jpg" alt="Chicago"
                             width="1100" height="500">
                    </center>
                    <div class="carousel-caption">
                        <h3>Chicago</h3>
                        <p>Thank you, Chicago!</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <center>
                        <img src="https://mdbootstrap.com/img/Photos/Horizontal/Nature/4-col/img%20(4).jpg" alt="New York"
                             width="1100" height="500">
                    </center>
                    <div class="carousel-caption">
                        <h3>New York</h3>
                        <p>We love the Big Apple!</p>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#demo" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a class="carousel-control-next" href="#demo" data-slide="next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>

    </section>


    {#{% include '../templates/StackOfMusic/footer.html' %}#}

{% endblock %}
</body>

</html>