StackOfMusic/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView, CompletedMusicRetrieveView, CompletedMusicDetailTemplateView, LikeMusicAPIView, \
    LikeMusicUpdateAPI, CreateCommentView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('<int:completed_music_id>/', CompletedMusicDetailTemplateView.as_view(), name='completed_music_detail'),
    path('RetrieveAPI/<int:completed_music_id>/', CompletedMusicRetrieveView.as_view(), name='completed_music_detail_api'),
    path('LikeMusicAPI/<int:completed_music_id>', LikeMusicAPIView.as_view(), name='like_music_api'),
    path('LikeMusicUpdateAPI/<int:pk>', LikeMusicUpdateAPI, name='like_music_update'),
    path('<int:completed_music_id>/CreateComment', CreateCommentView.as_view(), name='create_comment'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('create/', include('createmusic.urls', namespace='create_music')),
    path('instrument/search/', include('instrument.urls', namespace='instrument_search')),
    path('s3direct/', include('s3direct.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from .views import CreateUserView, CreateUserDoneView, UserLoginView, UserLogoutView, UserDetailView, \
    CopyrightTemplateView, UserWorkingProjects, MyPageListTemplateView, UserWorkingProjectsListView, \
    UserLikedMusicListView

app_name = 'accounts'


urlpatterns = [
    path('create/', CreateUserView.as_view(), name='accounts_create'),
    path('create/done', CreateUserDoneView.as_view(), name='accounts_create_done'),
    path('signin/', UserLoginView.as_view(), name='accounts_login'),
    path('signout/', UserLogoutView.as_view(url='http://localhost:8000'), name='accounts_logout'),
    path('mypage/<int:account_id>/myinfo', UserDetailView.as_view(), name='accounts_detail'),
    path('mypage/<int:account_id>/copyright/', CopyrightTemplateView.as_view(), name='accounts_copyright'),
    path('mypage/<int:account_id>/myworkingmusic/', UserWorkingProjectsListView.as_view(), name='accounts_working_projects'),
    path('mypage/<int:account_id>', MyPageListTemplateView.as_view(), name='account_list'),
    path('mypage/<int:account_id>/LkeMusic', UserLikedMusicListView.as_view(), name='user_liked_music'),
]

instrument/urls.py
from django.urls import path
from .views import MusicListView, InstrumentSearchResultListAPIView


app_name = 'instrument_search'

urlpatterns = [
    path('', MusicListView.as_view(), name='instrument_search'),
    path('api/<int:instrument_id>', InstrumentSearchResultListAPIView.as_view(), name='instrument_search_api'),
]

instrument/models.py
from django.db import models


class Instrument(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

music/models.py
from django.core.files.storage import FileSystemStorage
from django.db import models
from django.urls import reverse

from StackOfMusic import settings
from accounts.models import User


# class CustomFileField(models.FileField):
#     attr_class = FieldFile
#     interval = 0
#
#     def pre_save(self, model_instance, add):
#         file = super().pre_save(model_instance, add)
#         if file and not file._committed:
#             file.save(file.name, file.file, save=False)
#         return file
#
#     def set_interval(self, interval):
#         self.interval = interval


private_storage = FileSystemStorage(location=settings.STATIC_URL + settings.STATICFILES_LOCATION + '/')


class Genre(models.Model):
    name = models.CharField(max_length=5)

    def __str__(self):
        return self.name


class Music(models.Model):
    genre = models.ForeignKey('music.Genre', on_delete=models.CASCADE, related_name='music')
    owner = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='music_owner')
    title = models.CharField(max_length=30)
    album_jacket = models.ImageField(blank=True, upload_to='img')
    seed_file = models.FileField(upload_to='audiofile')
    completed_music = models.FileField(upload_to='audiofile', blank=True, null=True)
    instrument = models.ForeignKey('instrument.Instrument', on_delete=models.CASCADE, related_name='music', blank=True, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    liked_music = models.ManyToManyField('accounts.User', blank=True, related_name='music')
    participants = models.IntegerField(default=0)
    MUSIC_COMPLETED, MUSIC_NOT_COMPLETED = 0, 1
    MUSIC_OPTION = (
        (MUSIC_COMPLETED, '완성'),
        (MUSIC_NOT_COMPLETED, '미완성')
    )
    music_option = models.SmallIntegerField(choices=MUSIC_OPTION)
    BEFORE_UPDATE, UPDATING, AFTER_UPDATE = 0, 1, 2
    UPDATE_STATUS = (
        (BEFORE_UPDATE, '업데이트 전'),
        (UPDATING, '업데이트 중'),
        (AFTER_UPDATE, '업데이트 후'),
    )
    update_status = models.SmallIntegerField(choices=UPDATE_STATUS)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('create_music:working_music_detail', args=(self.pk,))

    @property
    def total_likes_user(self):
        return self.liked_music.count()

    def is_complete(self):
        return self.music_option == Music.MUSIC_COMPLETED

    def is_not_complete(self):
        return self.music_option == Music.MUSIC_NOT_COMPLETED


class SubMusic(models.Model):
    music = models.ForeignKey('music.Music', on_delete=models.CASCADE, related_name='sub_musics')
    contributor = models.ForeignKey('accounts.User', related_name='sub_music', on_delete=models.CASCADE)
    instrument = models.ForeignKey('instrument.Instrument', on_delete=models.CASCADE, related_name='sub_music')
    music_file = models.FileField(upload_to='audiofile')
    convert_music_file = models.FileField(upload_to=private_storage)
    create_date = models.DateTimeField(auto_now_add=True)
    ACCEPT, PENDING = 0, 1
    STATUS = (
        (ACCEPT, '머지'),
        (PENDING, '대기'),
    )
    status = models.SmallIntegerField(choices=STATUS)
    BEFORE_UPDATE, UPDATING, AFTER_UPDATE = 0, 1, 2
    UPDATE_STATUS = (
        (BEFORE_UPDATE, '업데이트 전'),
        (UPDATING, '업데이트 중'),
        (AFTER_UPDATE, '업데이트 후'),
    )
    update_status = models.SmallIntegerField(choices=UPDATE_STATUS)


class Comment(models.Model):
    music = models.ForeignKey('music.Music', on_delete=models.CASCADE, related_name='comment')
    user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name='comment')
    comment_text = models.TextField()

    def __str__(self):
        return self.comment_text
# Music.objects.prefetch_related('sub_musics').filter(instrument_id__in=[], sub_musics__instrument_id__in=[])
# class CompletedMusic(models.Model):

instrument/forms.py
from django import forms

from instrument.models import Instrument


class MusicSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word', max_length=100, required=False)
    instruments = forms.ModelMultipleChoiceField(Instrument.objects.all(),
                                                 widget=forms.CheckboxSelectMultiple, required=False)

instrument/views.py
from django.db.models import Q
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import ListView
from rest_framework import mixins, generics
from rest_framework.response import Response

from instrument.forms import MusicSearchForm
from music.models import Music
from .serializer import InstrumentSerializer


class MusicListView(ListView):
    template_name = 'instrument/instrument_list.html'
    context_object_name = 'music_list'
    model = Music

    def get_queryset(self):
        queryset = super(MusicListView, self).get_queryset()
        instrument_id_list = self.request.GET.getlist('instruments')
        search_word = self.request.GET.get('search_word')

        if search_word:
            queryset = queryset.filter(
                Q(title__contains=search_word) |
                Q(genre__name__contains=search_word) |
                Q(owner__username__contains=search_word)
            )

        if instrument_id_list:
            queryset = queryset.filter(
                Q(instrument_id__in=instrument_id_list) |
                Q(sub_musics__instrument_id__in=instrument_id_list)
            )

        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(MusicListView, self).get_context_data(object_list=None, **kwargs)
        context['form'] = MusicSearchForm(self.request.GET)
        return context

    def get(self, request, *args, **kwargs):
        return super(MusicListView, self).get(request, *args, **kwargs)


class InstrumentSearchResultListAPIView(mixins.ListModelMixin, generics.GenericAPIView):
    queryset = Music.objects.all()
    serializer = InstrumentSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def list(self, request, *args, **kwargs):
        data = request.GET.get('data')
        self.queryset = Music.objects.filter(instrument_id=data)
        queryset = self.filter_queryset(self.get_queryset())

        page = self.paginate_queryset(queryset)
        if page is not None:
            serializer = self.get_serializer(page, many=True)
            return self.get_paginated_response(serializer.data)

        serializer = self.get_serializer(queryset, many=True)
        return Response(serializer.data)

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(InstrumentSearchResultListAPIView, self).dispatch(request, *args, **kwargs)

instrument/templates/instrument/instrument_list.html
{% extends 'StackOfMusic/base.html' %}

{% block extra_scripts %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}

{% block extra_style %}
    <style>

        .boxes {
            margin-left: -40px;
            padding: 50px;
            background: white;
        }

        /*Checkboxes styles*/
        input[type="checkbox"] { display: none; }

        input[type="checkbox"] + label {
            display: block;
            position: relative;
            padding-left: 35px;
            margin-bottom: 20px;
            font: 18px/20px 'Open Sans', Arial, sans-serif;
            color: black;
            cursor: pointer;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
        }

        input[type="checkbox"] + label:last-child { margin-bottom: 0; }

        input[type="checkbox"] + label:before {
            content: '';
            display: block;
            width: 20px;
            height: 20px;
            border: 3px solid #6cc0e5;
            position: absolute;
            left: 0;
            top: 0;
            opacity: .6;
            -webkit-transition: all .12s, border-color .08s;
            transition: all .12s, border-color .08s;
        }

        input[type="checkbox"]:checked + label:before {
            width: 10px;
            top: -5px;
            left: 5px;
            border-radius: 0;
            opacity: 1;
            border-top-color: transparent;
            border-left-color: transparent;
            -webkit-transform: rotate(45deg);
            transform: rotate(45deg);
        }
    </style>
{% endblock %}
{% block content %}

    <!------ Include the above in your HEAD tag ---------->
    <body style="background-color: black">
    <div class="container">
        <div class="row" style="width: 1500px;">
            <div id="custom-search-input">
            <br>
                <form method="get">
                    <b><label for="id_search_word" style="color: whitesmoke">Search Word:</label></b>
                    <br><center>
                    <input type="text" name="search_word" maxlength="100" id="id_search_word" class="form-control input-lg" placeholder="Music Title" style="height: 50px;width:1200px;float: left"/>
                </center>
                    <span class="input-group-btn" style="display: inline;float: right">
                                <button class="btn btn-info btn-lg" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                    </span>

                    <div class="container">
                        <div class="row" style="padding: 50px;">
                            {% for instrument in form.instruments %}
                                <div style="width: 200px;">
                                    <input type="checkbox" name="instruments" value="{{ forloop.counter }}" id="{{ forloop.counter }}" style="float: left">
                                    <label style="color: whitesmoke" for="{{ forloop.counter }}">{{ instrument }}</label>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                </form>

            </div>
        </div>
        {% comment %}
        <div id="result_list" style="width: 100px;">
            {% for music in music_list %}
                {{ music.title }}
            {% endfor %}
        </div>
        {% endcomment %}
        <div class="container" >
            <table class="table table-striped custab" style="background-color: whitesmoke;margin-left: 30px;border-radius: 5px;">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th>Owner</th>
                    <th>Genre</th>
                </tr>
                </thead>
                {% for music in music_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>
                            {{ music.title }}
                        </td>
                        <td>
                            {{ music.owner }}
                        </td>
                        <td>{{ music.genre }}</td>
                    </tr>
                {% endfor %}

            </table>
        </div>
        <br>




    </div>
    </body>

{% endblock %}